# <center>Name: Saptarshi Sanyal
# <center> Email: saptarshi.edp@gmail.com
# <center>Programming Assignment_8
   

### 1. Write a Python Program to Add Two Matrices?

In [24]:
mat_1= [[1,2,3],[4,5,6]]

mat_2= [[7,8,9],[10,11,12]]

result = [[0,0,0],[0,0,0]]

# iterate through rows

for x in range(len(mat_1)):

   # iterate through columns

   for y in range(len(mat_1[0])):

        result[x][y] = mat_1[x][y] + mat_2[x][y]

for q in result:

    print(q)


[8, 10, 12]
[14, 16, 18]


### 2. Write a Python Program to Multiply Two Matrices?

In [31]:
import numpy as np
 

mat_1 = np.array([[1, 2],[5, 6]])
mat_2= np.array([[3, 4],[7, 8]])

 
result = np.matmul(mat_1,mat_2)

print(result)

[[17 20]
 [57 68]]


### 3. Write a Python Program to Transpose a Matrix?

In [34]:
mat_1 = np.array([[1, 2],[5, 6]])

print(mat_1)

print(mat_1.transpose())#Transpose

[[1 2]
 [5 6]]
[[1 5]
 [2 6]]


### 4.Write a Python Program to Sort Words in Alphabetic Order?

In [20]:
initial_str = "my hobby is stamp collection"
words = initial_str.split()
words.sort()
for word in words:
    print(word)




collection
hobby
is
my
stamp


### 5.Write a Python Program to Remove Punctuation From a String?

In [13]:
import string
initial_string = "Hi There!!!, I am Saptarshi Sanyal ! My email id is - saptarshi.edp@gmail.com"
print("String With Punctuation-",initial_string)
punc=string.punctuation
for c in initial_string:
    if c in punc:
        initial_string = initial_string.replace(c,"")
#string_wihtout_punctuation = string_with_punctuation.replace(string.punctuation,'')

print("String Without Punctuation-",initial_string)



String With Punctuation- Hi There!!!, I am Saptarshi Sanyal ! My email id is - saptarshi.edp@gmail.com
String Without Punctuation- Hi There I am Saptarshi Sanyal  My email id is  saptarshiedpgmailcom
