# Programing Assignment Number - 13
# Saptarshi Sanyal
# email id- saptarshi.edp@gmail.com

In [13]:
# Q 1.
# Q = Square root of [(2 * C * D)/H]


import math
C = 50
H = 30

D= input("Enter comma separated sequence of integers \n:")

list_1 = D.split(",")

Q = 0
temp=[]

for i in list_1:
    Q=math.sqrt(2*C*int(i)/H)
    temp.append(str(round(Q)))


result = ",".join(temp)

print(result)






Enter comma separated sequence of integers 
:100,150,180
18,22,24


In [21]:
# Q. 2
import numpy as np

dimension = input("Enter matrix dimension \n:")

list_1 = dimension.split(",")

list_int= [int(i) for i in list_1]

matrix_1=np.zeros(shape=tuple(list_int),dtype=np.int16)

row = list_int[0]
col = list_int[1]


for i in range(row):
    for j in range(col):
        matrix_1[i][j] = i*j
        
print("\n\nResultant Matrix-\n",matrix_1)

Enter comma separated sequence of integers 
:3,5
Initial matrix-

 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


Resultant Matrix-
 [[0 0 0 0 0]
 [0 1 2 3 4]
 [0 2 4 6 8]]


In [24]:
# Q. 3
input_str= input("Enter comma separated sequence of Words \n:")

list_1 = input_str.split(",")

print("Original_String-",list_1)

list_1.sort()
result_str= ",".join(list_1)
print("Result String-",result_str)

Enter comma separated sequence of Words 
:sap,kou,abc
Original_String- ['sap', 'kou', 'abc']
Result String- abc,kou,sap


In [27]:
# Q. 4
from collections import Counter

input_str= input("Enter space separated sequence of Words \n:")

list_1 = input_str.split(" ")

#We are creating a dictionary with counter method, then the words will be keys and occurances will be values. Since the 
# keys are unique, therfore we will have the unique words only in the keys.

unqiue_words = Counter(list_1)

result = " ".join(unqiue_words.keys())


print("Unique words-",result)

Enter space separated sequence of Words 
:sap peter peter linux java java linux
Result String- sap peter linux java


In [29]:
# Q. 5
input_str =input("enter the alpha numric string \n ")

char_count = 0
digit_count = 0


for i in input_str:
    if i.isalpha():
        char_count += 1
    elif i.isdigit():
        digit_count += 1
    else:
        pass
    
print("The number of characters:", char_count)
print("The number of digits:", digit_count)
    

enter the alpha numric string 
 gvhjgj 6786 fghh 7878 fghfhg 8678678
The number of characters: 16
The number of digits: 15


In [49]:
# Q.6 
import re

input_password = input("Enter comma separated sequence of Passwords \n:")

list_password = input_password.split(",")

valid_password=[]

regex_password = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[$#@])[A-Za-z\d$#@]{6,12}$"

match_re = re.compile(regex_password)


for password in list_password:
    
    
    if re.search(match_re, password):
        valid_password.append(password)
    else:
        pass
    
result_password= ",".join(valid_password)


print("Valid Password-",result_password)
    


Enter comma separated sequence of Passwords 
:Sap@1890,Saptarshi,Peter@123423,rIya$12
Valid Password- Sap@1890,Peter@123423,rIya$12
